project: pyexcel
name: pyexcel
author: C.W.
nick_name: pyexcel
copyright: copyright 2015-2020 Onni Software Ltd.
file_type: file type
copyright_year: 2015-2020
organisation: pyexcel
contact: info@pyexcel.org
license: New BSD
company: Onni Software Ltd.
branch: master
include_doctest: true
scm_host: github.com
extensions:
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.doctest'
  - 'sphinx.ext.intersphinx'
  - 'sphinx.ext.viewcode'
master: index
language: Python
lint_command: make lint
excluded_github_users:
  - chfw
